config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: [:update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  resources :inventories, except: [:update] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end 

  get 'shopping_lists/index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    user ||= User.new
    can :manage, :all if user.present?
    can :manage, Food, user: user if user.present?
    can :manage, Recipe, user: user if user.present?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: :food_id, dependent: :destroy

  validates :food, :measurement_unit, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :destroy

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def self.calculate_total_amount(recipe)
    total_amount = 0
    recipe.recipe_foods.includes(:food).each do |recipe_food|
      food = recipe_food.food
      total_amount += recipe_food.quantity * food.price
    end
    total_amount
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, foreign_key: :user_id, dependent: :destroy
  has_many :recipes, foreign_key: :user_id, dependent: :destroy

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    authorize! :destroy, @food
    @food.destroy!

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deleted.' }
    end
  end

  private

  def food_params
    params.require(:food).permit(:food, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(updated_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save!
        format.html { redirect_to recipe_path(@recipe), notice: 'Ingredient added successfully.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    authorize! :destroy, @recipe_food
    @recipe_food.destroy!

    respond_to do |format|
      format.html { redirect_to recipe_url, notice: 'Ingredient removed successfully.' }
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_foods).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]

  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe Added successfully.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    authorize! :destroy, @recipe

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe removed successfully.' }
    end
  end

  def show
    @foods = current_user.foods
    @recipe = current_user.recipes.includes(:recipe_foods).find(params[:id])
    @recipes = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update(public: false)
      flash.now[:notice] = 'Status changed to private.'
    else
      @recipe.update(public: true)
      flash.now[:notice] = 'Status changed to public'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @inventory = Inventory.find(params[:inventory_id])
    @shopping_list = @inventory.calculate_foods(@recipe)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<section class="hero">
    <h1>Food List</h1>
    <%= link_to 'Add Food', new_food_path %>

  <% if @foods.empty? %>
    <p>Please add foods using the Add Food button</p>
  <% else %>
  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.food %></td>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td>
            <% if can? :destroy, food %>
              <%= link_to 'Delete', food, data: { turbo_method: :delete, turbo_confirm: 'You are about to delete this food! Do you want to continue?' }, type:"button" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</section>

app/views/foods/new.html.erb
<section class="auth-forms">
  <div class="form-box">
    <div class="left-food"></div>
    <div class="right">
      <h2>Add Food</h2>
      <%= form_with(model: @food) do |f| %>
        <div class="field">
          <%= f.text_field :food, placeholder: "Food name", autofocus: true, required: true %>
        </div>

        <div class="field">
          <%= f.text_field :measurement_unit, placeholder: "Measurement unit", required: true %>
        </div>

        <div class="field">
          <%= f.text_field :price, placeholder: "Unit price", required: true %>
        </div>
        
        <div class="actions">
          <%= f.submit "Add Food" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/public_recipes/index.html.erb
<section class="hero">
  <h1>Public recipes list</h1>
  <% if @recipes.empty? %>
    <p>No public recipes for the moment!</p>
  <% else %>
  <ul>
    <% @recipes.includes(:user, :recipe_foods).each do |recipe| %>
      <li class="public-recipe-link">
        <%= link_to recipe_path(recipe.id) do %>
          <div class="public-recipe">
            <div class="recipe-owner">
              <p><%= recipe.name %></p>
              <p>by <%= recipe.user.name %></p>
            </div>
            <div class="recipe-details">
              <p>Total food items: <%= recipe.recipe_foods.length %> </p>
              <p>Total price: $<%= Recipe.calculate_total_amount(recipe) %></p>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <% end %>
</section>

app/views/recipes/index.html.erb
<section class="hero">
  <h1>Recipe List</h1>
  <%= link_to 'Add Recipe', new_recipe_path %>

  <% if @recipes.empty? %>
    <p>No recipes yet. Please add a recipe.</p>
  <% else %>
  <div> 
    <ul class="recipe-list">
      <% @recipes.each do |rcp| %>
        <%= link_to recipe_path(rcp.id) do %>
          <li>
            <div class="recipe-item">
              <h3><%= rcp.name %></h3>
              <% if can? :destroy, rcp %>
                <%= link_to 'Remove', rcp, data: { turbo_method: :delete, turbo_confirm: 'You are about to delete this recipe! Do you want to continue?' }, type:"button" %>
              <% end %>
            </div>
            <p><%= rcp.description %></p>
          </li>
        <% end %>
      <% end %> 
    </ul>
  </div>
  <% end %>
</section>

app/views/recipes/new.html.erb
<section class="auth-forms">
  <div class="form-box">
    <div class="left-recipe"></div>
    <div class="right">
      <h2>Create new recipe</h2>
      <%= form_with model: @recipe, method: :post, local: true do |f| %>
        <div class="field">
          <%= f.text_field :name, placeholder: "Recipe name", required: true %>
        </div>
        <div class="field">
          <%= f.text_field :cooking_time, placeholder: "Cooking time", required: true %>
        </div>
        <div class="field">
          <%= f.text_field :preparation_time, placeholder: "Preparation time", required: true %>
        </div>
        <div class="field">
          <%= f.text_area :description, placeholder: "Add description", required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Add Recipe" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="hero">
  <div>
    <h3><%= @recipe.name%></h3>
    <div>
      <div class="recipe-details">
        <div class="recipes">
          <div class="recipe-public">
            <p> Public: </p>
              <%= form_with url:recipe_path(@recipe.id), :method => :patch do |f| %>
                <%= f.check_box :public, checked: @recipe.public, onchange: "this.form.submit();" %>
              <% end %>
          </div>
          <p> Preparation time: <%= @recipe.preparation_time %> min</p>
        </div>
        <p> Cooking time: <%= @recipe.cooking_time %> min </p>
        <div class="recipe-buttons">
            <a id="openRecipeModal">Generate shopping list</a>
        </div>
      </div>
    </div>
  </div>

  <% if @recipe.recipe_foods.empty? %>
    <p>No ingredients added yet.</p>
  <% else %>
  <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.includes(:food).each do |recipe| %>
        <tr>
          <td><%= recipe.food.food %></td>
          <td><%= recipe.quantity %><%= recipe.food.measurement_unit %></td>
          <td>$<%= recipe.quantity * recipe.food.price %></td>
          <td>
            <% if can? :destroy, recipe %>
              <%= link_to 'Remove', recipe_recipe_food_path(@recipe.id, recipe.id), data: { turbo_method: :delete, turbo_confirm: 'You are about to remove this recipe food. Do you want to continue?' }, type:"button" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

  <div id="recipeModal" class="modal">
    <div>
      <span id='close-button'>x</span>
    </div>
    <div>
      <h2>Add recipe food</h2>
      <hr>
    </div>

    <div>
      <%= form_with url: recipe_recipe_foods_path(params[:id]), scope: :recipe_foods do |f| %>
        <% if @foods.empty? %>
          <p>No food added! Please add food.</p>
        <% else %>
          <div class="field">
            <%= f.select :food_id,@foods.collect { |food| [food.food, food.id] }, { :prompt => 'Select food'}, required: true %>
          </div>
          <div class="field">
            <%= f.number_field :quantity, placeholder: "Quantity", required: true %>
          </div>
          <div class="actions">
            <%= f.submit "Add quantity" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="inventoryModal" class="modal">
    <div>
      <span id="close-button-inventory">x</span>
    </div>
    <div>
      <h2>Generating Shopping List</h2>
      <hr>
    </div>

    <p>Choose an inventory</p>

    <div>
      <%= form_with url: shopping_lists_path, method: :get  do |f| %>
        <div class="field">
        </div>
        <div class="field">
          <%= f.hidden_field :recipe_id, value: @recipes.id, required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Generate" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shopping_lists/index.html.erb
<section>
  <div class="shopping">
    <h1>Shopping list</h1>
    <div class="shopping-details">
      <div>
        <p>Amount of food to buy: <%= @shopping_list.length %></p>
        <p>Total value of food needed: $<%= @shopping_list.inject(0) { |sum,item| sum + item[2] } %></p>
      </div>
      <div>
        <p>Recipe: <a href="<%= "/recipes/#{@recipe.id}" %>"><%= @recipe.name %></a></p>
      </div>
    </div>

    <% if @shopping_list.empty? %>
    <p>No food added yet.</p>
    <% else %>
      <table>
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @shopping_list.each do |shopping_item| %>
            <tr>
              <td><%= shopping_item[0] %></td>
              <td><%= shopping_item[1] %></td>
              <td><%= "$#{shopping_item[2]}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>